[[project]]
name = "MetalTools"
desc = "MetalTools provides a convenient, Swifty way of working with Metal. This library is heavily used in computer vision startups [ZERO10](https://zero10.ar) and [Prisma](https://prisma-ai.com)."
tags = ["iOS", "Metal"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/eugenebokhan/metal-tools" },
]

[[project]]
name = "CoreVideoTools"
desc = "A set of extensions and utilities to work with [CoreVideo](https://developer.apple.com/documentation/corevideo?language=obj) types."
tags = ["iOS", "CoreVideo"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/eugenebokhan/core-video-tools" },
]

[[project]]
name = "SharedGraphicsTools"
desc = "A set of tools for sharing graphics data on iOS."
tags = ["iOS", "Metal", "CoreGraphics", "Accelerate"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/eugenebokhan/shared-graphics-tools" },
]

[[project]]
name = "SwiftSnapshotTesting"
desc = "SwiftSnapshotTesting helps to check application's UI with a few lines of code. No need to manually manage reference images any more."
tags = ["iOS", "XCTest"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/eugenebokhan/swift-snapshot-testing" },
]

[[project]]
name = "AssetImportKit"
desc = "AssetImportKit is a cross platform library (macOS, iOS) that coverts the files supported by [Assimp](https://github.com/assimp/assimp) to [SceneKit](https://developer.apple.com/reference/scenekit) scenes."
tags = ["iOS", "SceneKit"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/eugenebokhan/asset-import-kit" },
]